### PR TITLE
SmartMatrix on 4 panels

### PR DESCRIPTION
**Pull request by GaryBoone**
Added support for 4 panels. 
• Demos include a 4 panel row (32 rows x 128 columns) and a 4 panel square (64x64). 
• Graphics, scroll text, and bitmaps work. 

Limitations:
• Scroll text rotation needs work. 0° works. Vertical orientations don't work. 270° works partially.
• Coordinate conversion from drawing to hardware should be correct for a column layout (128 rows x 32 columns), but it has not been tested. Nor is there a demo for that orientation.

Running the demos:
1. Edit SmartMatrix.h and uncomment the line with the resolution you want to demo, such as 
#include "MatrixHardware_KitV1_32x128.h"
2. Run the corresponding demo, such as Examples/FeatureDemo32x128.

### CODE REVIEW

**Comment by tabarious** [comment]
I know this is an older thread but I was interested in making a 64 x 64 display for a project and was using this. I was trying to display an entire 64 x 64 bitmap, but it was displaying two images 32 x 64. Almost as if it was still 32 x 128. I looked at the hardware file for 64 x 64 as saw that the matrix height and width were set to 32 and 128 respectively. I attempted to change them to 64 and 64 but it ended up displaying half of it and then the same half but a little off colored. I was wondering if you had come across this or would have a better idea of how to fix it. I haven't delved very deep and am somewhat new to it so it would probably take me a little time to see how everything is working exactly. Thanks for your help.

**Comment by GaryBoone** [comment]
Are you able to run the demos? It's been a few months, but IIRC, you have
to change both SmartMatrix.h and FeatureDemo64x64.ino, uncommenting the
lines that indicate 64x64 and commenting out the others.
FeatureDemo64x64.ino should already be set up correctly. Then
run FeatureDemo64x64.ino. That demo should show the current capabilities of
the 64x64 mode. From your description, it sounds like you just need to
adjust SmartMatrix.h.

Once you have the demo working, you'll have to study how the bitmaps are
loaded and displayed. I haven't looked at that code so can't suggest what
needs to be done.

--Gary

**Comment by tabarious** [comment]
Yes both are loading the 64 x 64 and I have run the feature demo, but it only demonstrates a 32 x 32. I have been looking a little closer and since the images are both smooshed it seems as if every other line is written on the top and bottom screen. It seems the bitmaps write only in 32 x 128 ( the second row would be at top). I'll try to look into it. Thanks for the help and the work you've already put into it.

**Comment by tabarious** [comment]
After doing a little troubleshooting it is what was expected. When drawing a bitmap the 128th pixel is on the top line of the lower screens (the third screen) as if they were in a row I will see if I can find where it is doing it in the hardware code or may just use a workaround to avoid headache. I can post what I find in case anyone else would like to do the same.

**Comment by embedded-creations** [comment]
There's another fork that extends Gary's changes and brings them into the 2.x version of the library: https://github.com/pixelmatix/SmartMatrix/pull/17

Sorry I haven't done much with any of the multiple screen forks so I can't point you in the right direction of how to draw bitmaps to anything larger than 32x32.

**Comment by LesterRomano** [comment]
Hi guys, Im kind of a beginner here at smartmatrix. Can anyone give me a tutorial on how to do animations? And I also want to expand my display into 64x64 but i don't really know how to reconfigure the library. Can you please lend a hand? Engineering student here.

**Comment by embedded-creations** [comment]
Hi Lester, there are a few tutorials I made on the Adafruit Learning System.  There's one on creating GIF animations:  
https://learn.adafruit.com/users/Pixelmatix

There's no official support for a 64x64 display.  You can try the code others have shared in this pull request and #17 but there's not much I can help you with as I'm not using the code myself.  If you ask some specific questions here maybe Gary or someone else will be able to help.

**Comment by LesterRomano** [comment]
Thanks mate! I really need the support for 64x64 display. Any help will do. please.

**Comment by Mozz164** [comment]
Just as an update to this thread, has anybody made any more progress with displaying .gif's and bitmap's on the 64x64 panel? I have four panels on the way and would like to know what ive got myself in for....   :)  Any help will be appreciated. Thanks

**Comment by embedded-creations** [comment]
@Mozz164 Displaying bitmaps should be relatively easy.  The bitmap example wont' work as is, but you can figure out the layer of the buffers and get it to work, falling back to a bunch of drawPixel calls if needed.  The GIF code was written for 32x32 GIFs specifically and I have no idea how difficult it will be to expand.  If you're working on this, please post to either a new issue or on our G+ community and I can try to help out but, I don't believe it's something anyone has tried before.

Also, the code in Pull Request #17 is more recent, but there is still no official support for >32x32 panels in SmartMatrix.

**Comment by embedded-creations** [comment]
Hi @GaryBoone, I'm working on support for larger displays and making the SmartMatrix Library more flexible with #25

**Comment by embedded-creations** [comment]
[SmartMatrix 3.0](https://github.com/pixelmatix/SmartMatrix/releases/tag/3.0.0) adds support for chaining/tiling displays with all features, e.g. rotation, Animated GIFs.  Thanks for your contributions in pioneering this feature!

**Pull request closed without merging**
