### PR TITLE
SmartMatrix on > 1 panels

### PR DESCRIPTION
**Pull request by mrwastl**
Ported GaryBoone's multi-panel patches to a current version of SmartMatrix (~ 2.1.0/master).

I'm driving a 96x64 display (six 32x32 panels), playback of streamed video output is rather smoothly and there's hardly any flickering - Pixelmatix seems to have optimised SmartMatrix a lot (compared to 1.x) !

My setup:
* Teensy 3.1: cpu speed set to 144 MHz (documentation: see README.md)
* Added a simple protocol to my library (serdisplib) which sends display content to a 'counterpart' library developed for arduino/teensy.
* A teensy program connects this library to my fork of SmartMatrix
* Communication is done using the Serial object (thus via standard full speed USB (12 mbit/s))
* Movie-content is generated using an old mplayer-hack that I've done some years ago which can use my library.
* Refresh rate is set to 80 (lower refresh rate would give even smoother video output but increased flickering. 80 seems to be a good compromise)
* Double buffering is used (swapBuffers(true)). Still the result is fast enough.
* I didn't use a naming scheme like 32x23.h for MatrixHardware_KitV1_32x32.h but I've used _generic.h instead (simpler when fooling around). I also pre-calculate some values like MATRIX_HEIGHT/WIDTH and even MATRIX_REFRESH_RATE (if not set by a user).

Limitations / annotations:
* I only need pixel-drawing operations, thus I haven't tested any printing / line-drawing functions
* The additions to serdisplib and the glue library for arduino/teensy which implement the protocol that is used for communication between my library and a teensy/arduino are not public yet (there's still a lot to be done)

### CODE REVIEW

**Comment by helgevh** [comment]
@mrwastl Nice work! You are right, the pixel code is running fine with my 2 32x32 panels. The text functions (scrolling text) seem to have some problems. The text in only shown in one of the two panels while the graphics work in both panels. I have tried to do some adjustments in MatrixForeground.cpp but I hat no success so far.

**Comment by mrwastl** [comment]
hi,

yeah i know.  i'm currently adding pixelmatrix' changes to my fork and 
i'm trying to fix the foreground-stuff too.

/wolfgang

**Comment by embedded-creations** [comment]
There's some code in https://github.com/pixelmatix/SmartMatrix/pull/2 that looks like it might support a foreground layer wider than 32 pixels.  This commit specifically:
https://github.com/SteveEisner/SmartMatrix/commit/4bfa76ff18bff90ff2238f3f89f14d1403ecb9d9

**Comment by helgevh** [comment]
Thanks, the code of https://github.com/SteveEisner/SmartMatrix/commit/4bfa76ff18bff90ff2238f3f89f14d1403ecb9d9 did the job. The feature demo (graphics & foreground text) is working fine now with two 32x32 panels.

**Comment by mrwastl** [comment]
yep, it works for a single row ( 32*n x 32*1 ) but not for more than one 
row (32*n x 32*m).

i think i'll have to rework the foreground-code a little bit (remove one 
dimension in the foregroundBitmap-array to not waste memory and still be 
able to rotate the display - memory IS an issue when using a 
96x64-display ...)

@louis: i've fooled around with the spectrum analyzer (just a a little 
bit - bars w/ and w/o outline-borders). it looks quite nice when using a 
96x64-display :)
and i've done small changes to make the examples resolution-agnostic.
it will be part of the code that will be uploaded when i'm done with the 
foreground-stuff.

/wolfgang

> Thanks, the code of SteveEisner@4bfa76f 
> <https://github.com/SteveEisner/SmartMatrix/commit/4bfa76ff18bff90ff2238f3f89f14d1403ecb9d9> 
> did the job. The feature demo (graphics & foreground text) is working 
> fine now with two 32x32 panels.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pixelmatix/SmartMatrix/pull/17#issuecomment-83774065>.
>

 > There's some code in #2 
<https://github.com/pixelmatix/SmartMatrix/pull/2> that looks like it 
might support a foreground layer wider than 32 pixels. This commit 
specifically:
 > SteveEisner@4bfa76f 
<https://github.com/SteveEisner/SmartMatrix/commit/4bfa76ff18bff90ff2238f3f89f14d1403ecb9d9>

**Comment by embedded-creations** [comment]
@mrwastl Sounds great, I'm excited to see it when you have code to share.  If you share a short video here or on the [SmartMatrix Users Community](http://pixl.mx/SmartMatrixUsers) that would be great as well.

**Comment by mrwastl** [comment]
hi louis,

i don't know the audio-functions/library, maybe you have more experience 
with it:

i wanted to fool around with stereo, but if i define a 2nd 
input/fft-connection, it seems to hang (even the 1st 
input/fft-connection doesn't do anything):

#define ADC_INPUT_PIN   A2
#define ADC_INPUT_PIN2  A1

AudioInputAnalog         input(ADC_INPUT_PIN);
AudioAnalyzeFFT256       fft;
AudioConnection          audioConnection(input, 0, fft, 0);

AudioInputAnalog         input2(ADC_INPUT_PIN2);
AudioAnalyzeFFT256       fft2;
AudioConnection          audioConnection2(input2, fft2);


=> nothing works anymore (even if i try to fill the matrix in setup() 
with a colour other than black: no reaction, just black).

maybe you have an idea / experience what may cause the problem here.
as said before: the first time that i've seen the audio-stuff was in 
your SpectrumAnalyzer-sketch :)

greetings
/wolfgang

**Comment by embedded-creations** [comment]
Hi Wolfgang, the only experience I have with the Audio library is running that sketch (I didn't even write it).  Maybe @jasoncoon has some ideas?  You can also try posting on the PJRC forum.

**Comment by jasoncoon** [comment]
I'll try adding another FFT for stereo.  Without looking, my guess would be memory is an issue, especially if you're running multiple panels.  I was unable to use the FFT1024 along with FastLED and SmartMatrix on a single panel due to lack of memory.

**Comment by mrwastl** [comment]
hi jason,

thanks for your answer.

I think the problem is that the audio library itself limits the inputs:

Supported Hardware
Audio Adaptor, for 16 bit stereo input and output.
Teensy 3.1 & 3.0 ADC, for 13 bit mono input.

The teensy itself would support 2 ADCs as far as i know, but the library 
only supports 1 analog input.

As soon as i define a 2nd AudioInputAnalog -> sketch stops working. I 
can define a 2nd fft and connection (2nd fft connected to the 1st 
input): no problem, but 2nd AudioInputAnalog -> nope.

Memory: I can deactivate the whole foreground-stuff in my git-fork -> 
this saves a lot of memory. So this should not be a memory issue.

Maybe I'll buy an audio-adaptor, which supports 16bit stereo input (it's 
not expensive and my audio-input breadboard-hardware seems to be a big 
crap anyway :)

**Comment by mrwastl** [comment]
New youtube-video with a modified SpectrumAnalyzer.ino in action.

The flickering is caused by the camera and NOT by the panel. The sound quality is poor (head phones mounted on recording camera :)

<a href="http://www.youtube.com/watch?feature=player_embedded&v=PNzRxckdhuc" target="_blank">Spectrum analyzer on a 96x64 RGB matrix panel</a>

**Comment by mrwastl** [comment]
(too stupid to read where i'm clicking ...)

**Comment by jasoncoon** [comment]
Looks great!  You should share your video with the SmartMatrix Users Community: https://plus.google.com/u/0/communities/105354523738870531811

**Comment by mrwastl** [comment]
committed new version of my fork (actually 3 commits because i'm still too stupid for git ...):

* foreground functions (scrolling) now works with chained panels (but only if rotation = 0, all other rotations are still unusable .. working on it)
* synced with pixelmatix' changes until feb 2 (but no merging yet because i've to find out how to do this w/o blowing up the whole stuff)
* some more modes for SpectrumAnalyzer (see video above)
* example MatrixClock3, which uses the internal RTC of a Teensy 3.0 or 3.1 and mimics 7-seg. displays and shows date and time.
* some improvements

**Comment by embedded-creations** [comment]
Thanks for the commits @mrwastl!  I wish I had a chained panel setup to try this (or the free time to set one up).

**Comment by mrwastl** [comment]
My fork now supports different colour spaces:
RGB565 and RGB332 (read documentation in MatrixHardware_KitV1_generic.h for more information).

This can be used to save memory when using bigger displays and still be able to compile memory-consuming programs.

**Comment by mrwastl** [comment]
@louis: how hard would it be to free port 10 for network (ethershield)?

there's

#define ADDX_TEENSY_PIN_1   10

but this is only used once in SmartMatrix.cpp (setting pinMode). If i change this setting to another port it doesn't work (I guess you are setting these 3-4 address-ports alltogether via DMA or so (i don't understand most of SmartMatrix.cpp ;-) ).

**Comment by embedded-creations** [comment]
The ADDX pins all need to be on the same MK20 Port, Port C.  If you're not using SD, Teensy Pin 15 is C0.  The other C pins are on the bottom side of the board, pins 27-30

**Comment by mrwastl** [comment]
oooh. now i get it.
ADDX_PIN_x and ADDX_TEENSY_PIN_x belong together.  ADDX_PIN_x is the bit index of PTCx.

thanks!

btw: i've managed to get AnimatedGIFs.ino running on my 96x64-display, but only with foreground-drawing disabled and colour space set to RGB332 (memory ...).

but it correctly managed to load 96x64 animated gifs!  the communication with the SD was a little bit flaky though (ethershield, i had to set CPU speed to 72 MHz, still sometimes reading errors, but at least it worked most of the time ...)

**Comment by embedded-creations** [comment]
It's great to hear that Craig's GIF code is working with >32x32 pixel GIFs.  I did some refactoring a few months ago to try to make it easier to use a non-32x32 GIF, did you have to change much beyond WIDTH and HEIGHT definitions?  Did you have to increase LZW_MAXBITS?

Paul Stoffregen is rewriting the SD library, which may help with the issues you're having:
https://forum.pjrc.com/threads/28057-Teensyduino-1-21-Released?p=70688&viewfull=1#post70688

I don't fully understand how the palette works with GIF encoding, but you might consider a indexed color background layer.  256 colors using the palette the GIF is using would most likely look better than those colors mapped to RGB332.

**Comment by embedded-creations** [comment]
I looked into the details and a GIF can have a 256-byte global color table as well as a local color table for each frame. No guarantee that using the global color table as your palette would look good for the whole animation.

**Comment by mrwastl** [comment]
I just changed WIDTH and HEIGHT definitions and it worked quite fine. But i've only tested a view GIFs that i've found on the internet. LZW_MAXBITS is unchanged. The RGB565/RGB332 colour spaces are kept quite simple and RGB888-'transparent' with the help of operator overloading on structs so that i can test programs/examples with my displays that wouldn't compile with RGB888 w/o the need of changing too much.

As far as i remember only GIF87a is limited to 256 colours (out of 16M). GIF89a added multiframe and multitile-support (with this one it is even possible to store truecolour images (though many image viewers/browers wouldn't support this ..)). But my experiences with implementing an GIF-de/encoder have been many years ago ...

SD: seems interesting. if i'm lucky it will be cpu-frequency invariant somewhen :)

**Comment by embedded-creations** [comment]
I'm not sure what LZW_MAXBITS does exactly, but I found I needed to increase that definition when playing a GIF with lots of subtle color changes.  I saw a band of pixels at the bottom of the screen that were displaying the wrong colors otherwise.  If you didn't notice that then you're probably fine.

**Comment by embedded-creations** [comment]
Hi @mrwastl, #25 should be of interest to you.  I have foreground working on 32x64 panels including rotation.  I'll work on C-shape chaining in a few weeks.

**Comment by embedded-creations** [comment]
This feature is implemented as part of #25

**Pull request closed without merging**
