### PR TITLE
Give an alternate way to port FastLED and GFX/NeoMatrix code to Smart…

### PR DESCRIPTION
**Pull request by marcmerlin**
…Matrix.

### CODE REVIEW

**Comment by embedded-creations** [comment]
Thanks Marc!

**Comment by marcmerlin** [comment]
BTW, I also got adafruit to add your lib to theirs since you support chips and panels they don't support: https://github.com/adafruit/RGB-matrix-Panel

**Comment by embedded-creations** [comment]
Thanks, but I'd prefer that SmartMatrix Library ESP32 functionality wasn't advertised in an Adafruit library, as it's alpha quality code right now, not easy to install (I'm assuming for the average Adafruit customer), and I have no plans at the moment to continue working on it

**Comment by marcmerlin** [comment]
Sorry about this, I didn't realize this
"no plans to continue working on it" == you're not interested in using ESP32 anymore and won't be working on teensylc further 
or
"no time to working on it currently due to other life priorities" (which would be quite understandable).

**Comment by embedded-creations** [comment]
It's somewhere between the two.  My next focus for SmartMatrix is making the APA102 to HUB75 adapter which came up during our initial conversation on the FastLED G+.  I want that for some personal projects in addition to thinking it's a good product, and would allow driving HUB75 panels from any dev board capable of running FastLED.  I haven't started on the design of the software for that product yet, but if it turns out to use an application on top of the SmartMatrix Library, then I'll likely continue improving the ESP32 port of SmartMatrix Library.  If it doesn't, and I base it on other software or write something simpler from scratch, then the port may sit idle for longer.

**Pull request merged**
