### PR TITLE
Use templates to allow full 48 bit color depth

### PR DESCRIPTION
**Pull request by gregfriedland**
After submitting the last pull request, I realized that what would probably better solve my issue (related to flickering at low values) is using 48bit colors all the way through. I hadn't fully realized originally that your library supports 48bit pwm internally, which is fantastic! So what I wanted was to store colors in the full 48bits in all places instead of just up-sampling from 24bits in the color correction table.

The right way to support several different color depths without code duplication seemed to be templating all the classes of the RGB type (`rgb24` or `rgb48`). This turned out to be a more arduous task than I had expected and ended up touching almost all the code in the some way because templated method definitions needed to move from the .cpp files to .h files (I put them in _Impl.h files) and of course the types needed to be changed everywhere to use the template type.

So this is a big pull request to review but hopefully of interest to you. Check out `examples/Gradient.ino` for a clear example of what things look like with 24 vs 48 bits at low intensities. Things look much smoother at 48.

A change I'd like to make soon is to allow 24bit colors to be used for the PWM (currently only 48bit works).

Cheers,
Greg

### CODE REVIEW

**Comment by embedded-creations** [comment]
This is great, and very timely!  My next step with 3.0 after improving some performance issues is to figure out how to use templates to allow for changing the color depth.  I'm focusing my efforts on the SM3.0 branch, so I'm not sure I will be able to apply your changes directly, but I'm sure they will be useful.

Can you share a little more about what you're doing so I can make sure that SM3.0 covers your use case?  Do you really need the full range of 48-bit color?  If Gradient.ino explains your use case, let me know and I'll just refer to that.

**Comment by gregfriedland** [comment]
Actually this was branched from the sm3.0 branch and I just incorporated your latest change from yesterday so it should merge cleanly.

Yes, I would really like to be able to use full 48bit color. All the stuff you've added under the hood is already there, so it was just a matter of propagating the 48bit type to be used everywhere. Except for the fact that there are lots of diffs everywhere, I didn't change any logic. 

Yes, Gradient.ino demonstrates why I want the 48bit color. If there's another way to smooth that out, let me know.

**Comment by embedded-creations** [comment]
Excellent, I'll try the demo and take a look at the code next week after I fix the performance issues.

**Comment by gregfriedland** [comment]
Sounds good. 

Just FYI: to avoid merging headaches you may want to look at it before you make make other major changes.

**Comment by embedded-creations** [comment]
Great work on this @gregfriedland!  Indeed it looked like an arduous task, it took me about 1.5 hours just to review (with some Googling to understand a few things in C++ I hadn't seen before).

24-bit color refresh is an easy fix, I'll commit that later.  I should also think if there's a more efficient way to handle this taking advantage of your rgb48-rgb24 conversion code.

I believe you removed support for dimming the Background layer, no big deal, I'll add it back.  It wasn't well documented and I just added it to FeatureDemo last week.  It uses a separate color correction table for the background layer so you can adjust the brightness of the overall display independently of the background layer.  This is useful if you want to have a bright text layer in the foreground and make it easier to read by dimming the background while keeping as much of the 24-bit color depth as possible.

A huge thank you for this pull request!

**Comment by embedded-creations** [comment]
FeatureDemo (and most other SmartMatrix sketches) won't work yet as there's errors for even basic functions like drawPixel.  I'll look into this, but it may have to be tomorrow.

**Comment by gregfriedland** [comment]
Great! Glad it was useful. It seemed to help noticeably with the project I'm working on. And you're right that the dithering is not longer necessary; this works much better.

Regarding 24bit color refresh, that can be done by templating on two rgb types:

    template <typename RGB_STORAGE, typename RGB_PWM>
    class SmartMatrix...

That will involve a bunch of changes but they should be 95% search and replace and I wouldn't expect many issues this time. I can look at this if you like but it sounds like you may have an easier way.

Regarding dimming the Background, yeah I admit I didn't quite understand the use of this so I think I removed that functionality. Sorry about that. :) There's probably other stuff I broke as you just discovered. Let me know if you want me to look at any of it.

**Comment by embedded-creations** [comment]
@gregfriedland Thanks for the offer, let me give it a try first and I'll be sure to let you know if I'm stuck.

The easy way for 24-bit color refresh is just this inside the loop of `loadMatrixBuffers()`

```
        if(latchesPerRow == 8) {
            temp0red >>= 8;
            temp0green >>= 8;
            temp0blue >>= 8;
            temp1red >>= 8;
            temp1green >>= 8;
            temp1blue >>= 8;
        }
```

**Comment by embedded-creations** [comment]
The Gradient example doesn't tell me enough about your use case, as I can make an identical (to my eyes) gradient with a 24-bit color by setting the brightness to 10% and multiplying `max` by 10.  If all you need is 48-bit layer color and 36/48-bit refresh in SmartMatrix 3.0, it will be there.  If you really need a mix of bright and dim pixels on the screen at the same time, that's probably the best bet.  If you need nice fades from dark to light and vice versa, rgb24 with interpolation might work for you with less RAM but (I assume) more CPU.  I modified Fadecandy firmware to run on SmartMatrix, and that's what it's doing.
https://github.com/pixelmatix/SmartMatrix_Fadecandy
https://github.com/pixelmatix/fadecandy

Happy to discuss more about your project here or by email if you want.

**Comment by embedded-creations** [comment]
Found an interesting bug.  Sketches using storage_depth=48 and color correction shouldn't work as `colorCorrection()` is using the 16-bit color as an index to the 256-entry color correction arrays.  I think it's because `ccmode` inside SMLayerBackground should be `this->ccmode` but haven't had time to make sure.  I will fix this and ponder what to do for color correction when storage_depth=48 (probably disable color correction) tomorrow.

Telling you here as the fix I just checked in for background brightness breaks Gradient.

**Pull request merged**
