### PR TITLE
Comment out unused code to squelsh compilation warnings

### PR DESCRIPTION
**Pull request by marcmerlin**
/home/merlin/Arduino/libraries/SmartMatrix_me/src/SmartMatrixMultiplexedCalcEsp32_Impl.h:398:7: warning: unused variable 'o0' [-Wunused-variable]
     } o0;

### CODE REVIEW

**Comment by marcmerlin** [comment]
If you set compiler warnings to all in your arduino config, you'll see those. I like them on so that I can catch stupid mistakes.

**Comment by marcmerlin** [comment]
fair small fixup patch to add?

**Comment by embedded-creations** [comment]
I'm in Hawaii at the moment, so my attention's not really on this.  If that code truly isn't necessary (for all users, not just you), it would be better just to delete the code.  I took a quick look and it seems that way, but I'm not 100% sure.

**Comment by marcmerlin** [comment]
replaced by https://github.com/pixelmatix/SmartMatrix/pull/75

**Pull request closed without merging**
