### PR TITLE
Font Improvements

### PR DESCRIPTION
**Pull request by liebman**
This PR implements some of the font improvements listed in #30. 
-  fonts > 8 bits
- optional font pointers

### CODE REVIEW

**Comment by liebman** [comment]
Marked as a work-in-progress as while this works for test on the background layer it does not work on the scrolling layer.

**Comment by liebman** [comment]
This covers part of #30

**Comment by liebman** [comment]
I think this is ready for review.

**Comment by embedded-creations** [comment]
Thanks for the PR!  I'm not going to be able to try this out any time soon, but I do look forward to testing it when I have time.

**Comment by liebman** [comment]
Hmmm - looks like I'm access font elements outside of the MatrixFont* files....  I think I'll add needed method so that the font struct stays opaque.

**Comment by liebman** [comment]
@embedded-creations Before I update this to 4.0, would this change be of interest?

**Comment by embedded-creations** [comment]
It might be of interest to someone, but not to me personally.  I think the more modern workflow of building a font using the Adafruit_GFX font tools and importing it just into the sketch, not into the library is better for most people.  Have you tried that out yet?

https://github.com/pixelmatix/SmartMatrix/wiki/Features#adafruit_gfx-layers

**Comment by liebman** [comment]
I'll switch to that. Closing.

**Pull request closed without merging**
