### PR TITLE
Minor doc edits

### PR DESCRIPTION
**Pull request by marcmerlin**

### CODE REVIEW

**Comment by embedded-creations** [comment]
Thanks Marc, I'll take a look at these when I have time (might not be soon)

**Comment by marcmerlin** [comment]
not urgent, you're welcome to take part or none of it, just sent it your way in case it helps.
Top level README is personal and I understand you may have specific ideas on what should be in it, and how or where :)

**Comment by marcmerlin** [comment]
would you be ok integrating this, as is or as modified by you?

**Comment by marcmerlin** [comment]
@embedded-creations  this would still be useful IMO

**Comment by embedded-creations** [comment]
I made some edits, and added some more detailed documentation on panels supported to docs.pixelmatix.com to keep the README tidy.  Thanks!

**Comment by marcmerlin** [comment]
thanks.

**Pull request merged**
